# Generated by Django 5.0.7 on 2024-07-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetail',
            name='efficiency_whkm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='fast_charge_kmh',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='range_km',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cardetail',
            name='top_speed_kmh',
            field=models.IntegerField(),
        ),
    ]
